name: Build SuperBLT Windows

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install CMake
      run: |
        choco install -y cmake

    - name: Add MSBuild
      uses: microsoft/setup-msbuild@v3

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -A x64 -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=RelWithDebInfo
        msbuild SuperBLT.sln /t:Build /p:Configuration=RelWithDebInfo

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SuperBLT-x64
        path: |
          build/**/*.dll
          build/**/*.exe
          build/**/*.pdb
